### ISSUE TITLE
Problème de validation avec les author rend=margin

### ISSUE THREAD

**Issue by StellaLouis** [OBVIL/mythographie#4]
author rend=margin = Solution provisoire : pour les auteurs et traducteurs implicites de citations. changé en note place=margin avec [<author></author>] pour contenu et [Translator : <author></author>] pour contenu traducteur. Le tout contenu dans un <bibl>. Solution définitive : autoriser author rend=margin. Systématiquement dans un <bibl> inline

**Comment by AnneLHuet** [comment]
Ne font pas parti du texte, doivent être en `<note>` avec un resp="editor" : 
```xml
<bibl><note place="margin">[<author key="Boileau" resp="editor">Boileau</author>]</note></bibl>
```
devient : 
```xml
<note place="margin" resp="editor">
<bibl>[<author key="Boileau">Boileau</author>]</bibl>
</note>
```
